// @ts-check
/**
 * The extra SLO windows the alerts need (B094). B093's recording rules
 * (infra/observability/slo/rules.yaml) cover 5m, 1h, 6h and 3d; the slow-burn alerts pair 6h with a
 * 30m short window, so this writes `slo:sli_error:ratio_rate30m` and `slo:burn_rate:30m` for every
 * SLO into infra/alerts/recording/slo-30m.rules.yaml, from the same SLO files and in the same form.
 *
 * Usage: node infra/alerts/slo-windows.mjs [--check]
 * `--check` exits 1 when the file is out of date (`pnpm alerts:lint` runs the same check).
 *
 * Owns: the 30m recording rules. Must not: change B093's SLO files or its rules.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parse, stringify } from 'yaml';

/** The repository root. */
export const REPO = fileURLToPath(new URL('../../', import.meta.url));
/** B093's SLO files, relative to the root. */
export const SLO_DIR = 'infra/observability/slo';
/** The file this writes, relative to the root. */
export const WINDOWS_FILE = 'infra/alerts/recording/slo-30m.rules.yaml';
/** Windows recorded here, on top of B093's. */
export const EXTRA_WINDOWS = Object.freeze(['30m']);

/** @typedef {{ name: string, objective: number, owner: string, sli: { good: string, total: string } }} Slo */

/**
 * Every SLO under `root`, sorted by name. B093's tests validate the files; this reads only the
 * fields it needs and throws naming the file when one is missing.
 * @param {string} [root]
 * @returns {Slo[]}
 */
export function readSlos(root = REPO) {
  const dir = join(root, SLO_DIR);
  return readdirSync(dir)
    .filter((f) => f.endsWith('.slo.yaml'))
    .map((f) => {
      const slo = /** @type {Partial<Slo> | null} */ (parse(readFileSync(join(dir, f), 'utf8')));
      if (
        slo === null ||
        typeof slo.name !== 'string' ||
        typeof slo.objective !== 'number' ||
        typeof slo.owner !== 'string' ||
        typeof slo.sli?.good !== 'string' ||
        typeof slo.sli.total !== 'string'
      ) {
        throw new Error(`${SLO_DIR}/${f}: needs name, objective, owner and sli {good, total}`);
      }
      return /** @type {Slo} */ (slo);
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * The recording rules file for `slos`, as YAML text.
 * @param {readonly Slo[]} slos
 * @returns {string}
 */
export function sloWindowRules(slos) {
  /** @param {string} selector @param {string} window */
  const rate = (selector, window) => `sum by (env) (rate(${selector}[${window}]))`;
  const groups = slos.map((slo) => ({
    name: `slo-windows-${slo.name}`,
    interval: '1m',
    rules: [
      ...EXTRA_WINDOWS.map((w) => ({
        record: `slo:sli_error:ratio_rate${w}`,
        expr: `1 - (${rate(slo.sli.good, w)} / ${rate(slo.sli.total, w)})`,
        labels: { slo: slo.name },
      })),
      ...EXTRA_WINDOWS.map((w) => ({
        record: `slo:burn_rate:${w}`,
        expr: `slo:sli_error:ratio_rate${w}{slo="${slo.name}"} / (1 - ${slo.objective})`,
        labels: { slo: slo.name },
      })),
    ],
  }));
  const header =
    '# Generated by infra/alerts/slo-windows.mjs from infra/observability/slo/*.slo.yaml (B094): the\n' +
    "# 30m window of each SLO's error ratio and burn rate, next to B093's 5m, 1h, 6h and 3d.\n" +
    '# Do not edit: change an SLO file and run `node infra/alerts/slo-windows.mjs`.\n';
  return header + stringify({ groups }, { lineWidth: 0 });
}

/**
 * Writes (or with `check`, compares) the file under `root`; returns the exit code.
 * @param {{ root?: string, check?: boolean }} [options]
 * @returns {number}
 */
export function run({ root = REPO, check = false } = {}) {
  const text = sloWindowRules(readSlos(root));
  const file = join(root, WINDOWS_FILE);
  if (check) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      // missing: out of date
    }
    if (current === text) return 0;
    process.stderr.write(`${WINDOWS_FILE} is out of date: run node infra/alerts/slo-windows.mjs\n`);
    return 1;
  }
  writeFileSync(file, text);
  return 0;
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = run({ check: process.argv.includes('--check') });
}
