// Single ESLint flat config for the whole repo (B001). Workspaces must not add
// their own config or switch these rules off; change them here, in review.
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

const WORKSPACE_IMPORT_PATTERNS = [
  {
    // B011's simulator is a public subpath of the testkit's "exports" map.
    group: ['@centcom/*/*', '!@centcom/testkit/sim'],
    message:
      'Import a workspace package by its name only; its package.json "exports" map is the public surface.',
  },
  {
    group: ['**/apps/*/**', '**/packages/*/**'],
    message: 'Do not reach into another workspace by path; depend on it by package name.',
  },
];

// B004: configuration is read once, by the config loader, at the entrypoint. (Core ESLint's
// no-process-env is deprecated, so the same rule is built from no-restricted-* rules.)
const ENV_MESSAGE =
  'Read configuration with defineConfig() from @centcom/core (B004); only the config loader and apps/*/src/main.ts read process.env.';

// Ways around no-restricted-properties: aliasing `process`, reaching it through `globalThis` or
// `global`, and computed access (`process[key]`). A guardrail against mistakes, not a sandbox:
// `Reflect.get(process, 'env')` and similar indirection are left to review.
const ENV_SYNTAX = [
  "VariableDeclarator[id.type='Identifier'][init.type='Identifier'][init.name='process']",
  "AssignmentExpression[right.type='Identifier'][right.name='process']",
  "MemberExpression[object.name=/^(globalThis|global)$/][property.name='process']",
  "MemberExpression[object.name='process'][computed=true]",
].map((selector) => ({ selector, message: ENV_MESSAGE }));

// B088: the admin console renders untrusted API text and holds a staff token. No raw HTML, no
// eval, and no browser storage anywhere in its code.
const ADMIN_SYNTAX = [
  {
    selector: "JSXAttribute[name.name='dangerouslySetInnerHTML']",
    message: 'Render API values as text (B088): no dangerouslySetInnerHTML.',
  },
  {
    selector: 'AssignmentExpression[left.property.name=/^(innerHTML|outerHTML)$/]',
    message: 'Render API values as text (B088): no innerHTML or outerHTML.',
  },
  {
    selector: 'CallExpression[callee.property.name=/^(insertAdjacentHTML|write|writeln)$/]',
    message: 'Render API values as text (B088): no HTML strings into the document.',
  },
];
const ADMIN_STORAGE = [
  { name: 'localStorage', message: 'The admin console keeps nothing in browser storage (B088).' },
  { name: 'sessionStorage', message: 'The admin console keeps nothing in browser storage (B088).' },
  { name: 'indexedDB', message: 'The admin console keeps nothing in browser storage (B088).' },
];

export default defineConfig([
  globalIgnores([
    '**/node_modules/',
    '**/dist/',
    '**/coverage/',
    'contracts/',
    'plan/',
    'site/',
    'tools/plan/',
    // Generated by packages/contracts/scripts/generate.ts (B003); never edited by hand.
    'packages/contracts/src/generated/',
    // Files that must fail lint; tools/repo/lint-fixtures.test.ts lints them on purpose.
    'tools/lint-fixtures/',
  ]),
  js.configs.recommended,
  tseslint.configs.strict,
  {
    files: ['**/*.{ts,tsx,mts,cts,js,mjs,cjs}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'error',
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'process', importNames: ['env'], message: ENV_MESSAGE },
            { name: 'node:process', importNames: ['env'], message: ENV_MESSAGE },
          ],
          patterns: WORKSPACE_IMPORT_PATTERNS,
        },
      ],
      'no-restricted-properties': [
        'error',
        { object: 'process', property: 'env', message: ENV_MESSAGE },
      ],
      'no-restricted-syntax': ['error', ...ENV_SYNTAX],
    },
  },
  {
    // The config loader (B004), service entrypoints and repo tooling may read the environment,
    // and so may deploy scripts under infra/ (B094's alerts:render reads contact points).
    files: ['apps/*/src/main.ts', 'packages/core/src/config/**', 'tools/**', 'infra/**/*.mjs'],
    rules: {
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'no-restricted-imports': ['error', { patterns: WORKSPACE_IMPORT_PATTERNS }],
    },
  },
  {
    // Node globals for scripts and config files that run directly under Node.
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: { globals: { process: 'readonly', console: 'readonly', URL: 'readonly' } },
  },
  {
    // Console output is allowed only in process entrypoints and repo tooling, never in library code.
    files: ['apps/*/src/main.ts', 'tools/**/*.{ts,mjs}'],
    rules: { 'no-console': 'off' },
  },
  {
    // B088: the admin console's code (tests may inspect storage to prove it stays empty).
    files: ['apps/admin/src/**/*.{ts,tsx}'],
    rules: {
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-restricted-syntax': ['error', ...ENV_SYNTAX, ...ADMIN_SYNTAX],
      'no-restricted-globals': ['error', ...ADMIN_STORAGE],
      'no-restricted-properties': [
        'error',
        { object: 'process', property: 'env', message: ENV_MESSAGE },
        {
          object: 'document',
          property: 'cookie',
          message: 'The admin console sets no cookies (B088).',
        },
        ...ADMIN_STORAGE.map(({ name, message }) => ({
          object: 'window',
          property: name,
          message,
        })),
        ...ADMIN_STORAGE.map(({ name, message }) => ({
          object: 'globalThis',
          property: name,
          message,
        })),
      ],
    },
  },
]);
