#!/usr/bin/env python3
"""Renders plan/lanes/**.json into readable markdown: per-lane briefs, plan indexes, graph, contract matrix, integration gates."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from planlib import *

def bullets(items): return '\n'.join(f'- {x}' for x in items) if items else '- none'
def code_list(items): return ', '.join(f'`{x}`' for x in items) if items else 'none'

def card_md(c, unblocks, titles, ms='-'):
    deps = ', '.join(f'[{d}]({d}.md) {titles[d]}' for d in c['depends_on']) or 'none (can start immediately)'
    unb = ', '.join(f'[{d}]({d}.md)' for d in unblocks) or 'none'
    gate = c.get('unblocks_gate') or '-'
    return f'''# {c['id']} · {c['title']}

| | |
|---|---|
| **Plan** | {c['plan']} |
| **Milestone** | {ms} |
| **Phase** | {c['phase']} |
| **Size** | {c['size']} ({SIZE_DAYS[c['size']]} day{'s' if SIZE_DAYS[c['size']] > 1 else ''} max) |
| **Role** | {c['role']} |
| **Gate** | {gate} |
| **Depends on** | {deps} |
| **Unblocks** | {unb} |
| **Implements** | {code_list(c['implements'])} |
| **Consumes** | {code_list(c['consumes'])} |

> Read first: [`plan/GUIDELINES.md`](../GUIDELINES.md) (strict rules for every lane) and the contracts listed above in [`contracts/`](../../contracts/).

## Goal
{c['goal']}

## In scope
{bullets(c['scope_in'])}

## Out of scope
{bullets(c['scope_out'])}

## Build against (no counterpart needed)
{c['build_against']}

## Deliverables
{bullets([f'`{d}`' for d in c['deliverables']])}

## Interfaces (the only surface other lanes may use)
{bullets(c['interfaces'])}

## Acceptance criteria
{chr(10).join(f'{i}. {x}' for i, x in enumerate(c['acceptance'], 1))}

## Tests required
{bullets(c['tests'])}

## Guardrails (MUST / MUST NOT)
{bullets(c['guardrails'])}

## Failure modes
{bullets(c['failure_modes'])}
{('## Notes' + chr(10) + c['notes'] + chr(10)) if c.get('notes') else ''}
## Definition of done
Everything in [GUIDELINES §8](../GUIDELINES.md) plus every acceptance item above covered by a test.
'''

def main():
    skel, index = load_skeleton(), load_index()
    all_cards = {p: load_cards(p) for p in PLANS}
    MS = load_milestones(); META = load_milestone_meta()
    stats = {}
    for plan in PLANS:
        lanes = skel[plan]; cards = all_cards[plan]
        titles = {l['id']: l['title'] for l in lanes}
        rev = {l['id']: [] for l in lanes}
        for l in lanes:
            for d in l['depends_on']: rev[d].append(l['id'])
        outdir = os.path.join(PLAN, plan); os.makedirs(outdir, exist_ok=True)
        for fn in os.listdir(outdir):
            if fn.endswith('.md'): os.remove(os.path.join(outdir, fn))
        for l in lanes:
            c = cards.get(l['id'])
            if c: open(os.path.join(outdir, l['id'] + '.md'), 'w').write(card_md(c, rev[l['id']], titles, MS.get(l['id'], '-')))
        layers = topo_layers({l['id']: l['depends_on'] for l in lanes})
        days, path = critical_path(lanes)
        total = sum(SIZE_DAYS[l['size']] for l in lanes)
        stats[plan] = dict(layers=layers, days=days, path=path, total=total)
        phases = []
        for l in lanes:
            if l['phase'] not in phases: phases.append(l['phase'])
        rows = []
        for ph in phases:
            rows.append(f'\n### {ph}\n\n| ID | Lane | M | Size | Role | Depends on | Implements | Gate |\n|---|---|:-:|:-:|---|---|---|:-:|')
            for l in [x for x in lanes if x['phase'] == ph]:
                c = cards.get(l['id'], {})
                rows.append(f"| [{l['id']}]({l['id']}.md) | {l['title']} | {MS.get(l['id'], '-')} | {l['size']} | {l['role']} | {', '.join(l['depends_on']) or '-'} | {', '.join(c.get('implements', [])) or '-'} | {c.get('unblocks_gate') or '-'} |")
        name = 'Backend' if plan == 'backend' else 'Client'
        repo = 'Centcom-backend' if plan == 'backend' else 'Centcom'
        sizes = {s: sum(1 for l in lanes if l['size'] == s) for s in 'SML'}
        open(os.path.join(outdir, 'README.md'), 'w').write(f'''# {name} plan · {len(lanes)} lanes ({PREFIX[plan]}001-{PREFIX[plan]}{len(lanes):03d})

Repo: `{repo}` · Rules: [`plan/GUIDELINES.md`](../GUIDELINES.md) · Format: [`plan/LANE_CARD_SPEC.md`](../LANE_CARD_SPEC.md) · Connection points: [`contracts/`](../../contracts/index.json)

- **{len(lanes)} lanes**: {sizes['S']} small (≤1 d), {sizes['M']} medium (≤3 d), {sizes['L']} large (≤5 d) · {total} person-days of work in total
- **{len(layers)} dependency layers** · critical path **{days} days** (see [`GRAPH.md`](../GRAPH.md)) · parallelism in layer 1: {len(layers[0])} lanes can start on day one
- Every lane card is independent: it names its inputs (contracts), outputs (deliverables), and how to build with no counterpart (`build_against`).
- **No lane in this plan depends on a lane in the other plan.** The two sides meet only at contract IDs.

{chr(10).join(rows)}
''')
    # graph
    g = ['# Dependency graph\n', 'Generated by `tools/plan/build_plan.py`. Layer N can start once everything in earlier layers it depends on is done; lanes in the same layer never depend on each other.\n']
    for plan in PLANS:
        s = stats[plan]; lanes = {l['id']: l for l in skel[plan]}
        g.append(f'\n## {plan.capitalize()}\n')
        g.append(f"Critical path: **{s['days']} days** → " + ' → '.join(s['path']) + '\n')
        g.append(f"Serial effort: {s['total']} person-days. With enough people the plan can finish in about the critical-path length; with N people expect roughly max(critical path, {s['total']}/N) days.\n")
        g.append('\n| Layer | Lanes (can run in parallel) |\n|---:|---|')
        for i, layer in enumerate(s['layers'], 1):
            g.append(f"| {i} | {', '.join(layer)} |")
        # phase-level mermaid
        phase_of = {i: l['phase'] for i, l in lanes.items()}
        edges = set()
        for i, l in lanes.items():
            for d in l['depends_on']:
                if phase_of[d] != phase_of[i]: edges.add((phase_of[d], phase_of[i]))
        g.append('\n```mermaid\nflowchart LR')
        ph_id = {p: 'P%d' % n for n, p in enumerate(dict.fromkeys(phase_of.values()))}
        for p, i in ph_id.items(): g.append(f'  {i}["{p}"]')
        for a, b in sorted(edges): g.append(f'  {ph_id[a]} --> {ph_id[b]}')
        g.append('```')
    open(os.path.join(PLAN, 'GRAPH.md'), 'w').write('\n'.join(g) + '\n')
    # contract matrix
    m = ['# Contract matrix\n', 'Which lanes realise or rely on each contract. Generated by `tools/plan/build_plan.py`; this is the map of every connection point between the two plans.\n',
         '| Contract | Kind | Backend implements | Backend consumes | Client implements | Client consumes |', '|---|---|---|---|---|---|']
    for c in index['contracts']:
        cells = []
        for p in PLANS:
            im = sorted(i for i, cd in all_cards[p].items() if c['id'] in cd.get('implements', []))
            co = sorted(i for i, cd in all_cards[p].items() if c['id'] in cd.get('consumes', []))
            cells += [', '.join(im) or '-', ', '.join(co) or '-']
        m.append(f"| `{c['id']}` | {c['kind']} | {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} |")
    open(os.path.join(PLAN, 'CONTRACT_MATRIX.md'), 'w').write('\n'.join(m) + '\n')
    # roadmap (milestones) and feature map
    order = MS_ORDER
    byid = {l['id']: l for p in PLANS for l in skel[p]}
    def mstats(m, plan):
        ids = [i for i in byid if MS.get(i) == m and byid[i]['plan'] == plan]
        days = sum(SIZE_DAYS[byid[i]['size']] for i in ids)
        # longest dependency chain inside the milestone
        memo = {}
        def best(i):
            if i in memo: return memo[i]
            d = [best(x) for x in byid[i]['depends_on'] if x in ids]
            memo[i] = SIZE_DAYS[byid[i]['size']] + (max(d) if d else 0); return memo[i]
        return ids, days, (max((best(i) for i in ids), default=0))
    rm = ['# Roadmap\n', 'What ships, in what order. A **milestone** is something a person can demo. Both sides work **in parallel**: the backend track starts at M0 and is ready by the time the client reaches M3, so M1 and M2 (the free, client-only product) can ship and be tested while the server is being built.\n',
          '```', 'time ->   M0 ───► M1 ───► M2 ───► M3 ───► M4 ───► M5 ───► M6', 'client    scaffold  solo    LAN      accounts teams    fleet    launch', '          + mocks   agent   multi-   + relay  + money  + polish', '                    in TUI  player   client   + web', 'backend   scaffold  ·······················build the server in parallel·········', '          + mocks   (identity, relay, billing lanes run alongside M1-M2)', '```\n',
          '**Recommended first release: M1 + M2** (client only, no server, no accounts). It proves the core idea (several people and agents on one project) before any backend or billing exists.\n',
          '| Milestone | What ships | Lanes (client / backend) | Person-days (client / backend) | Gate |', '|---|---|---|---|---|']
    for m in order:
        ci, cd, cc = mstats(m, 'client'); bi, bd, bc = mstats(m, 'backend')
        rm.append(f"| **{m}** {META[m]['name']} | {META[m]['goal']} | {len(ci)} / {len(bi)} | {cd} / {bd} | {META[m]['gate']} |")
    def cum(m, plan):
        upto = order[:order.index(m) + 1]
        ids = [i for i in byid if MS.get(i) in upto and byid[i]['plan'] == plan]
        days = sum(SIZE_DAYS[byid[i]['size']] for i in ids)
        memo = {}
        def best(i):
            if i in memo: return memo[i]
            d = [best(x) for x in byid[i]['depends_on'] if x in ids]
            memo[i] = SIZE_DAYS[byid[i]['size']] + (max(d) if d else 0); return memo[i]
        return days, max((best(i) for i in ids), default=0)
    rm += ['\n## How long will it take?\n', 'Rough calendar time to reach a milestone, per side, from the lane sizes: `weeks = max(longest dependency chain, person-days / (people x 0.8)) / 5`. The 0.8 allows for review, meetings and context switching. These are planning numbers, not promises.\n',
           '| Reach | Side | Person-days | Longest chain (days) | 2 people | 3 people | 4 people |', '|---|---|--:|--:|--:|--:|--:|']
    for m in ('M2', 'M3', 'M4', 'M6'):
        for plan in ('client', 'backend'):
            d, ch = cum(m, plan)
            if d == 0: continue
            w = lambda n: max(ch, d / (n * 0.8)) / 5
            rm.append(f"| {m} | {plan} | {d} | {ch} | {w(2):.0f} wk | {w(3):.0f} wk | {w(4):.0f} wk |")
    rm.append('')
    for m in order:
        ci, cd, cc = mstats(m, 'client'); bi, bd, bc = mstats(m, 'backend')
        rm += [f"\n## {m} · {META[m]['name']}", f"\n{META[m]['goal']}\n", f"- **Who:** {META[m]['who']}  ·  **Gate:** {META[m]['gate']}", f"- **Demo:** {META[m]['demo']}"]
        if META[m]['exit']:
            rm.append('- **Done when:**'); rm += [f'  - {x}' for x in META[m]['exit']]
        rm.append(f"- **Effort:** client {cd} person-days (longest chain {cc} d) · backend {bd} person-days (longest chain {bc} d)")
        for plan, ids in (('client', ci), ('backend', bi)):
            if ids:
                rm.append(f"\n**{plan.capitalize()} lanes ({len(ids)}):**\n")
                rm += [f"- [{i}]({plan}/{i}.md) {byid[i]['title']} ({byid[i]['size']})" for i in ids]
    open(os.path.join(PLAN, 'ROADMAP.md'), 'w').write('\n'.join(rm) + '\n')
    feats = load_features()
    ft = ['# Feature map\n', 'The same product feature seen from both sides: which backend lanes, which client lanes, which contracts connect them, and when it ships. Use this to find who to talk to.\n', '| Feature | M | Backend lanes | Client lanes | Contracts |', '|---|:-:|---|---|---|']
    link = lambda ids, plan: ', '.join(f'[{i}]({plan}/{i}.md)' for i in ids) or '-'
    for f in sorted(feats, key=lambda f: (order.index(f['milestone']), f['name'])):
        ft.append(f"| **{f['name']}**<br><sub>{f['what']}</sub> | {f['milestone']} | {link(f['backend'], 'backend')} | {link(f['client'], 'client')} | {', '.join('`'+c+'`' for c in f['contracts']) or '-'} |")
    open(os.path.join(PLAN, 'FEATURES.md'), 'w').write('\n'.join(ft) + '\n')
    # integration gates
    gates = {'G0': ('Contract freeze', 'Contracts reviewed and locked; `tools/plan/validate_contracts.py` passes; both repos hold identical contracts (`lock.py --compare`).'),
             'G1': ('Hello', 'Client authenticates via the device flow against the real API and fetches `/v1/me`.'),
             'G2': ('Tunnel', 'Client connects to the real relay: handshake, heartbeat, forced disconnect, resume.'),
             'G3': ('Command post', 'Two real clients: host + guest, queue → approve → agent runs → events fan out, end-to-end encrypted.'),
             'G4': ('Money', 'Checkout → webhook → entitlement flips → relay unlocked; quota warnings arrive.'),
             'G5': ('Fleet', 'Three clients, branch mode, file locks, presence, notifications, webhooks.'),
             'G6': ('Launch', 'Load + chaos + security review, installer + auto-update, runbooks, both conformance suites green.')}
    t = ['# Integration gates\n', 'Joint, scripted checks run against real builds of both sides. Each gate lists the lanes that declare they unblock it. The provider-side script lives in lane B100, the consumer-side in lane C100.\n']
    for gid, (name, desc) in gates.items():
        t.append(f'\n## {gid} · {name}\n\n{desc}\n')
        for p in PLANS:
            ls = sorted(i for i, cd in all_cards[p].items() if cd.get('unblocks_gate') == gid)
            t.append(f'- **{p}** lanes: {", ".join(ls) or "-"}')
    open(os.path.join(PLAN, 'INTEGRATION.md'), 'w').write('\n'.join(t) + '\n')
    n = sum(len(v) for v in all_cards.values())
    print(f'rendered {n} cards; critical path backend {stats["backend"]["days"]}d, client {stats["client"]["days"]}d')

if __name__ == '__main__':
    main()
