#!/usr/bin/env python3
"""Renders plan/lanes/**.json into readable markdown: per-lane briefs, plan indexes, graph, contract matrix, integration gates."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from planlib import *

def bullets(items): return '\n'.join(f'- {x}' for x in items) if items else '- none'
def code_list(items): return ', '.join(f'`{x}`' for x in items) if items else 'none'

def card_md(c, unblocks, titles):
    deps = ', '.join(f'[{d}]({d}.md) {titles[d]}' for d in c['depends_on']) or 'none (can start immediately)'
    unb = ', '.join(f'[{d}]({d}.md)' for d in unblocks) or 'none'
    gate = c.get('unblocks_gate') or '-'
    return f'''# {c['id']} · {c['title']}

| | |
|---|---|
| **Plan** | {c['plan']} |
| **Phase** | {c['phase']} |
| **Size** | {c['size']} ({SIZE_DAYS[c['size']]} day{'s' if SIZE_DAYS[c['size']] > 1 else ''} max) |
| **Role** | {c['role']} |
| **Gate** | {gate} |
| **Depends on** | {deps} |
| **Unblocks** | {unb} |
| **Implements** | {code_list(c['implements'])} |
| **Consumes** | {code_list(c['consumes'])} |

> Read first: [`plan/GUIDELINES.md`](../GUIDELINES.md) (strict rules for every lane) and the contracts listed above in [`contracts/`](../../contracts/).

## Goal
{c['goal']}

## In scope
{bullets(c['scope_in'])}

## Out of scope
{bullets(c['scope_out'])}

## Build against (no counterpart needed)
{c['build_against']}

## Deliverables
{bullets([f'`{d}`' for d in c['deliverables']])}

## Interfaces (the only surface other lanes may use)
{bullets(c['interfaces'])}

## Acceptance criteria
{chr(10).join(f'{i}. {x}' for i, x in enumerate(c['acceptance'], 1))}

## Tests required
{bullets(c['tests'])}

## Guardrails (MUST / MUST NOT)
{bullets(c['guardrails'])}

## Failure modes
{bullets(c['failure_modes'])}
{('## Notes' + chr(10) + c['notes'] + chr(10)) if c.get('notes') else ''}
## Definition of done
Everything in [GUIDELINES §8](../GUIDELINES.md) plus every acceptance item above covered by a test.
'''

def main():
    skel, index = load_skeleton(), load_index()
    all_cards = {p: load_cards(p) for p in PLANS}
    stats = {}
    for plan in PLANS:
        lanes = skel[plan]; cards = all_cards[plan]
        titles = {l['id']: l['title'] for l in lanes}
        rev = {l['id']: [] for l in lanes}
        for l in lanes:
            for d in l['depends_on']: rev[d].append(l['id'])
        outdir = os.path.join(PLAN, plan); os.makedirs(outdir, exist_ok=True)
        for fn in os.listdir(outdir):
            if fn.endswith('.md'): os.remove(os.path.join(outdir, fn))
        for l in lanes:
            c = cards.get(l['id'])
            if c: open(os.path.join(outdir, l['id'] + '.md'), 'w').write(card_md(c, rev[l['id']], titles))
        layers = topo_layers({l['id']: l['depends_on'] for l in lanes})
        days, path = critical_path(lanes)
        total = sum(SIZE_DAYS[l['size']] for l in lanes)
        stats[plan] = dict(layers=layers, days=days, path=path, total=total)
        phases = []
        for l in lanes:
            if l['phase'] not in phases: phases.append(l['phase'])
        rows = []
        for ph in phases:
            rows.append(f'\n### {ph}\n\n| ID | Lane | Size | Role | Depends on | Implements | Gate |\n|---|---|:-:|---|---|---|:-:|')
            for l in [x for x in lanes if x['phase'] == ph]:
                c = cards.get(l['id'], {})
                rows.append(f"| [{l['id']}]({l['id']}.md) | {l['title']} | {l['size']} | {l['role']} | {', '.join(l['depends_on']) or '-'} | {', '.join(c.get('implements', [])) or '-'} | {c.get('unblocks_gate') or '-'} |")
        name = 'Backend' if plan == 'backend' else 'Client'
        repo = 'Centcom-backend' if plan == 'backend' else 'Centcom'
        sizes = {s: sum(1 for l in lanes if l['size'] == s) for s in 'SML'}
        open(os.path.join(outdir, 'README.md'), 'w').write(f'''# {name} plan · 100 lanes ({PREFIX[plan]}001-{PREFIX[plan]}100)

Repo: `{repo}` · Rules: [`plan/GUIDELINES.md`](../GUIDELINES.md) · Format: [`plan/LANE_CARD_SPEC.md`](../LANE_CARD_SPEC.md) · Connection points: [`contracts/`](../../contracts/index.json)

- **{len(lanes)} lanes**: {sizes['S']} small (≤1 d), {sizes['M']} medium (≤3 d), {sizes['L']} large (≤5 d) · {total} person-days of work in total
- **{len(layers)} dependency layers** · critical path **{days} days** (see [`GRAPH.md`](../GRAPH.md)) · parallelism in layer 1: {len(layers[0])} lanes can start on day one
- Every lane card is independent: it names its inputs (contracts), outputs (deliverables), and how to build with no counterpart (`build_against`).
- **No lane in this plan depends on a lane in the other plan.** The two sides meet only at contract IDs.

{chr(10).join(rows)}
''')
    # graph
    g = ['# Dependency graph\n', 'Generated by `tools/plan/build_plan.py`. Layer N can start once everything in earlier layers it depends on is done; lanes in the same layer never depend on each other.\n']
    for plan in PLANS:
        s = stats[plan]; lanes = {l['id']: l for l in skel[plan]}
        g.append(f'\n## {plan.capitalize()}\n')
        g.append(f"Critical path: **{s['days']} days** → " + ' → '.join(s['path']) + '\n')
        g.append(f"Serial effort: {s['total']} person-days. With enough people the plan can finish in about the critical-path length; with N people expect roughly max(critical path, {s['total']}/N) days.\n")
        g.append('\n| Layer | Lanes (can run in parallel) |\n|---:|---|')
        for i, layer in enumerate(s['layers'], 1):
            g.append(f"| {i} | {', '.join(layer)} |")
        # phase-level mermaid
        phase_of = {i: l['phase'] for i, l in lanes.items()}
        edges = set()
        for i, l in lanes.items():
            for d in l['depends_on']:
                if phase_of[d] != phase_of[i]: edges.add((phase_of[d], phase_of[i]))
        g.append('\n```mermaid\nflowchart LR')
        ph_id = {p: 'P%d' % n for n, p in enumerate(dict.fromkeys(phase_of.values()))}
        for p, i in ph_id.items(): g.append(f'  {i}["{p}"]')
        for a, b in sorted(edges): g.append(f'  {ph_id[a]} --> {ph_id[b]}')
        g.append('```')
    open(os.path.join(PLAN, 'GRAPH.md'), 'w').write('\n'.join(g) + '\n')
    # contract matrix
    m = ['# Contract matrix\n', 'Which lanes realise or rely on each contract. Generated by `tools/plan/build_plan.py`; this is the map of every connection point between the two plans.\n',
         '| Contract | Kind | Backend implements | Backend consumes | Client implements | Client consumes |', '|---|---|---|---|---|---|']
    for c in index['contracts']:
        cells = []
        for p in PLANS:
            im = sorted(i for i, cd in all_cards[p].items() if c['id'] in cd.get('implements', []))
            co = sorted(i for i, cd in all_cards[p].items() if c['id'] in cd.get('consumes', []))
            cells += [', '.join(im) or '-', ', '.join(co) or '-']
        m.append(f"| `{c['id']}` | {c['kind']} | {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} |")
    open(os.path.join(PLAN, 'CONTRACT_MATRIX.md'), 'w').write('\n'.join(m) + '\n')
    # integration gates
    gates = {'G0': ('Contract freeze', 'Contracts reviewed and locked; `tools/plan/validate_contracts.py` passes; both repos hold identical contracts (`lock.py --compare`).'),
             'G1': ('Hello', 'Client authenticates via the device flow against the real API and fetches `/v1/me`.'),
             'G2': ('Tunnel', 'Client connects to the real relay: handshake, heartbeat, forced disconnect, resume.'),
             'G3': ('Command post', 'Two real clients: host + guest, queue → approve → agent runs → events fan out, end-to-end encrypted.'),
             'G4': ('Money', 'Checkout → webhook → entitlement flips → relay unlocked; quota warnings arrive.'),
             'G5': ('Fleet', 'Three clients, branch mode, file locks, presence, notifications, webhooks.'),
             'G6': ('Launch', 'Load + chaos + security review, installer + auto-update, runbooks, both conformance suites green.')}
    t = ['# Integration gates\n', 'Joint, scripted checks run against real builds of both sides. Each gate lists the lanes that declare they unblock it. The provider-side script lives in lane B100, the consumer-side in lane C100.\n']
    for gid, (name, desc) in gates.items():
        t.append(f'\n## {gid} · {name}\n\n{desc}\n')
        for p in PLANS:
            ls = sorted(i for i, cd in all_cards[p].items() if cd.get('unblocks_gate') == gid)
            t.append(f'- **{p}** lanes: {", ".join(ls) or "-"}')
    open(os.path.join(PLAN, 'INTEGRATION.md'), 'w').write('\n'.join(t) + '\n')
    n = sum(len(v) for v in all_cards.values())
    print(f'rendered {n} cards; critical path backend {stats["backend"]["days"]}d, client {stats["client"]["days"]}d')

if __name__ == '__main__':
    main()
