/**
 * SLO recording rules (B093): reads `infra/observability/slo/*.slo.yaml` and writes
 * `infra/observability/slo/rules.yaml`, the Prometheus (Mimir) recording rules for each SLO:
 *
 * - `slo:sli_error:ratio_rate<w>{slo}`: the share of bad events over each window w (5m, 1h, 6h,
 *   3d), `1 - good / total`, by env;
 * - `slo:burn_rate:<w>{slo}`: that share over the error budget (`1 - objective`), the
 *   multi-window burn rates B094's alerts read.
 *
 * Usage: `pnpm --filter @centcom/core gen:slo-rules` (add `--check` to fail when rules.yaml is out of
 * date). `infra/observability/slo/rules.test.yaml` checks the rules with `promtool test rules`.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parse, stringify } from 'yaml';

/** One SLO file. */
export interface Slo {
  name: string;
  objective: number;
  window: string;
  owner: string;
  sli: { good: string; total: string };
}

/** The windows burn rates are recorded over. */
export const BURN_WINDOWS = ['5m', '1h', '6h', '3d'] as const;

export const SLO_DIR = fileURLToPath(new URL('../../../infra/observability/slo/', import.meta.url));
export const RULES_FILE = join(SLO_DIR, 'rules.yaml');

/** `value` as an SLO; throws naming the file and the problem. */
export function checkSlo(file: string, value: unknown): Slo {
  const fail = (problem: string): never => {
    throw new Error(`${file}: ${problem}`);
  };
  if (typeof value !== 'object' || value === null) return fail('not a mapping');
  const v = value as Record<string, unknown>;
  const keys = Object.keys(v).sort().join(',');
  if (keys !== 'name,objective,owner,sli,window') {
    fail('needs exactly name, objective, window, sli and owner');
  }
  if (typeof v['name'] !== 'string' || !/^[a-z][a-z0-9-]{2,40}$/.test(v['name'])) {
    fail('name must be lower-case words joined by dashes');
  }
  if (typeof v['objective'] !== 'number' || !(v['objective'] > 0 && v['objective'] < 1)) {
    fail('objective must be a ratio between 0 and 1');
  }
  if (typeof v['window'] !== 'string' || !/^\d+[dh]$/.test(v['window'])) {
    fail('window must be like 30d');
  }
  if (typeof v['owner'] !== 'string' || v['owner'] === '') fail('owner is required');
  const sli = v['sli'] as Record<string, unknown> | null;
  if (
    typeof sli !== 'object' ||
    sli === null ||
    typeof sli['good'] !== 'string' ||
    typeof sli['total'] !== 'string' ||
    Object.keys(sli).length !== 2
  ) {
    fail('sli must be {good, total}, two series selectors');
  }
  return v as unknown as Slo;
}

/** Every SLO in `dir`, by name. */
export function readSlos(dir: string = SLO_DIR): Slo[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.slo.yaml'))
    .sort()
    .map((f) => checkSlo(f, parse(readFileSync(join(dir, f), 'utf8'))))
    .sort((a, b) => a.name.localeCompare(b.name));
}

const rate = (selector: string, window: string): string =>
  `sum by (env) (rate(${selector}[${window}]))`;

/** The rules file for `slos`, as YAML text. */
export function sloRules(slos: readonly Slo[]): string {
  const groups = slos.map((slo) => ({
    name: `slo-${slo.name}`,
    interval: '1m',
    rules: [
      ...BURN_WINDOWS.map((w) => ({
        record: `slo:sli_error:ratio_rate${w}`,
        expr: `1 - (${rate(slo.sli.good, w)} / ${rate(slo.sli.total, w)})`,
        labels: { slo: slo.name },
      })),
      ...BURN_WINDOWS.map((w) => ({
        record: `slo:burn_rate:${w}`,
        expr: `slo:sli_error:ratio_rate${w}{slo="${slo.name}"} / (1 - ${slo.objective})`,
        labels: { slo: slo.name },
      })),
    ],
  }));
  const header =
    '# Generated by packages/core/scripts/gen-slo-rules.ts from infra/observability/slo/*.slo.yaml.\n' +
    '# Do not edit: change an SLO file and run `pnpm --filter @centcom/core gen:slo-rules`.\n';
  return header + stringify({ groups }, { lineWidth: 0 });
}

function main(): number {
  const text = sloRules(readSlos());
  if (process.argv.includes('--check')) {
    const current = readFileSync(RULES_FILE, 'utf8');
    if (current !== text) {
      process.stderr.write(
        'infra/observability/slo/rules.yaml is out of date: run gen:slo-rules\n',
      );
      return 1;
    }
    return 0;
  }
  writeFileSync(RULES_FILE, text);
  return 0;
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main();
}
