/**
 * Config docs generator (B004): renders docs/config.md and .env.example from the config schemas,
 * so the documented keys, types, defaults and secret flags always match the code.
 *
 * Usage: tsx scripts/gen-config-docs.ts [--check]
 *   (default)  rewrite docs/config.md and .env.example at the repository root
 *   --check    exit 1 if either differs from a fresh render (nothing is written)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { baseEnvSchema } from '../src/config/base.js';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const COMMAND = 'pnpm --filter @centcom/core gen:config-docs';

/** One documented group of keys. */
export interface ConfigSection {
  title: string;
  owner: string;
  schema: z.ZodObject;
}

/** Every documented section. A lane that declares keys with defineConfig appends its schema here. */
export const SECTIONS: readonly ConfigSection[] = [
  {
    title: 'Base configuration',
    owner: 'B004, `baseConfig()` in `@centcom/core`',
    schema: baseEnvSchema,
  },
];

/** Everything the docs say about one key. */
export interface KeyDoc {
  key: string;
  type: string;
  defaultValue: string | null;
  required: boolean;
  secret: boolean;
  description: string;
  example: string;
}

/** Reads type, default, required and secret for every key of an environment schema. */
export function describeKeys(schema: z.ZodObject): KeyDoc[] {
  const json = z.toJSONSchema(schema, { io: 'input' }) as {
    properties?: Record<string, Record<string, unknown>>;
    required?: string[];
  };
  const required = new Set(json.required ?? []);
  return Object.entries(schema.shape).map(([key, field]): KeyDoc => {
    const p = json.properties?.[key] ?? {};
    const parsed = (field as z.ZodType).safeParse(undefined);
    const defaultValue = parsed.success && parsed.data !== undefined ? String(parsed.data) : null;
    const type =
      typeof p.envType === 'string'
        ? p.envType
        : Array.isArray(p.enum)
          ? p.enum.map((v) => `\`${String(v)}\``).join(' | ')
          : typeof p.type === 'string'
            ? p.type
            : 'string';
    return {
      key,
      type,
      defaultValue,
      required: required.has(key),
      secret: p.secret === true,
      description: typeof p.description === 'string' ? p.description : '',
      example: typeof p.example === 'string' ? p.example : (defaultValue ?? ''),
    };
  });
}

const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function renderMarkdown(sections: readonly ConfigSection[]): string {
  const out = [
    `<!-- GENERATED by packages/core/scripts/gen-config-docs.ts (B004). Do not edit; run \`${COMMAND}\`. -->`,
    '',
    '# Configuration',
    '',
    'Every service reads its configuration once, at startup, through `defineConfig` (`@centcom/core`,',
    'lane B004). Invalid configuration stops the process before it opens a port, with one error that',
    'lists every problem by key name, never by value.',
    '',
    '- Blank values count as unset.',
    '- Any key can instead be given as `KEY_FILE=<path>` (Docker and Fly secrets). The file wins over',
    '  `KEY`. A UTF-8 byte-order mark and trailing newlines are removed; other whitespace is part of',
    '  the value. A file that is missing, unreadable, not a regular file or over 64 KiB is reported',
    '  against `KEY_FILE`, without its path.',
    '- Secrets print as `[redacted]` in logs, errors and JSON; code reads them with `reveal()`.',
    '- Only the config loader and service entrypoints may read `process.env` (enforced by lint).',
    '- A lane that adds keys declares them with `defineConfig` in its own module and adds a section to',
    '  `packages/core/scripts/gen-config-docs.ts`.',
    '',
  ];
  for (const section of sections) {
    out.push(`## ${section.title}`, '', `Owner: ${section.owner}.`, '');
    out.push(
      '| Key | Type | Default | Required | Secret | Description |',
      '|---|---|---|---|---|---|',
    );
    for (const k of describeKeys(section.schema)) {
      out.push(
        `| \`${k.key}\` | ${cell(k.type)} | ${k.defaultValue === null ? '' : `\`${cell(k.defaultValue)}\``} | ${k.required ? 'yes' : 'no'} | ${k.secret ? 'yes' : 'no'} | ${cell(k.description)} |`,
      );
    }
    out.push('');
  }
  return out.join('\n');
}

function renderEnvExample(sections: readonly ConfigSection[]): string {
  const out = [
    `# GENERATED by packages/core/scripts/gen-config-docs.ts (B004). Do not edit; run \`${COMMAND}\`.`,
    '# Names and harmless local-development placeholders only: never commit real values.',
    '# Any KEY can instead be given as KEY_FILE=<path to a file holding the value>.',
  ];
  for (const section of sections) {
    out.push('', `# ${section.title}`);
    for (const k of describeKeys(section.schema)) out.push(`${k.key}=${k.example}`);
  }
  return `${out.join('\n')}\n`;
}

/** The generated files, keyed by path relative to the repository root. */
export function renderConfigDocs(
  sections: readonly ConfigSection[] = SECTIONS,
): Map<string, string> {
  return new Map([
    ['docs/config.md', renderMarkdown(sections)],
    ['.env.example', renderEnvExample(sections)],
  ]);
}

/** CLI: returns the process exit code. */
export function main(args: readonly string[], root: string = REPO_ROOT): number {
  const files = renderConfigDocs();
  if (args.includes('--check')) {
    const stale = [...files].filter(([path, content]) => {
      const file = join(root, path);
      return !existsSync(file) || readFileSync(file, 'utf8') !== content;
    });
    if (stale.length > 0) {
      process.stderr.write(
        `Config docs are out of date; run \`${COMMAND}\`: ${stale.map(([p]) => p).join(', ')}\n`,
      );
      return 1;
    }
    process.stdout.write('Config docs are up to date.\n');
    return 0;
  }
  for (const [path, content] of files) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), content, 'utf8');
  }
  process.stdout.write(`Wrote ${[...files.keys()].join(' and ')}.\n`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
